config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord

  has_many :cat_rental_requests,
    class_name: :CatRentalRequest,
    primary_key: :id,
    foreign_key: :cat_id

end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :status, presence: true, inclusion: %w(PENDING APPROVED DENIED)
  validates :start_date, :end_date, :cat_id, presence: true
  validate :does_not_overlap_approved_request


  belongs_to :cat,
    class_name: :Cat,
    primary_key: :id,
    foreign_key: :cat_id,
    dependent: :destroy

  def overlapping_requests

  end

  def overlapping_approved_requests

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])

    render :show
  end

  def new
    @cat = Cat.new
    
    render :new
  end

  def edit
    @cat = Cat.find_by(id: params[:id])

    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end

  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  private

  def cat_params
    params.require(:cats).permit(:name, :color, :sex, :description, :birth_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>


<form action= "<%= action_url %>" method="post">
  <% if cat.persisted?  %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input type="text" name="cats[name]" value="<%= cat.name %>">

  <label for="date">Date</label>
  <input type="date" name="cats[birth_date]" value="<%= cat.birth_date %>">

  <label for="color">Color</label>
  <input type="text" name="cats[color]" value="<%= cat.color %>">

  <label for="sex">Sex</label>
    <select name="cats[sex]">
      <option disabled <%= cat.sex ? "" : "selected" %> >--Choose Sex--</option>
      <option value="f" <%= cat.sex == "f" ? "selected" : "" %> >Female</option>
      <option value="m" <%= cat.sex == "m" ? "selected" : "" %> >Male</option>
    </select>
  <label for="description">Description</label>
  <textarea name="cats[description]">

     <%= cat.description %>

  </textarea>

  <input type="submit" name="" value=" <%= cat.persisted? ? 'Update cat' : 'Add cat' %>">
</form>

app/views/cats/edit.html.erb
<h2>Edit Cat</h2>

<%= render 'form', cat: @cat %>
<!-- <form action= '<%= cat_url(@cat) %>' method="post">
  <input type="hidden" name="_method" value="PATCH">

  <label for="name">Name</label>
  <input type="text" name="cats[name]" value="<%= @cat.name %>">

  <label for="date">Date</label>
  <input type="date" name="cats[birth_date]" value="<%= @cat.birth_date %>">

  <label for="color">Color</label>
  <input type="text" name="cats[color]" value="<%= @cat.color %>">

  <label for="sex">Sex</label>
    <select name="cats[sex]">
      <option disabled>-Choose Sex-</option>
      <option value="f" <%= @cat.sex == "f" ? "selected" : "" %> >Female</option>
      <option value="m" <%= @cat.sex == "m" ? "selected" : "" %> >Male</option>
    </select>
  <label for="description">Description</label>
  <textarea name="cats[description]">

     <%= @cat.description %>

  </textarea>

  <input type="submit" name="" value="Update cat">
</form> -->

app/views/cats/index.html.erb
<% @cats.each do |cat| %>
  <%= link_to 'Show Cat', cat_url(cat)  %>
  <%= cat.name %>
<% end %>

app/views/cats/new.html.erb
<h2>Add Cat</h2>

<%= render 'form', cat: @cat %>

<!--

<form action= '<%= cats_url %>' method="post">
  <label for="name">Name</label>
  <input type="text" name="cats[name]" value="">

  <label for="date">Date</label>
  <input type="date" name="cats[birth_date]" value="">

  <label for="color">Color</label>
  <input type="text" name="cats[color]" value="">

  <label for="sex">Sex</label>
    <select name="cats[sex]">
      <option disabled selected>-Choose Sex-</option>
      <option value="f">Female</option>
      <option value="m">Male</option>
    </select>
  <label for="description">Description</label>
  <textarea name="cats[description]"></textarea>


  <input type="submit" name="" value="submit cat">
</form> -->

app/views/cats/show.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>NAME</th>
    <th>COLOR</th>
    <th>BIRTH DATE</th>
    <th>SEX</th>
    <th>DESCRIPTION</th>
  </tr>
  <tr>
    <td><%= @cat.id %></td>
    <td><%= @cat.name %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>